export const reviews = [
    {
        id: 1,
        tutorId: 1,
        studentId: 'user-alex-johnson',
        studentName: 'Alex Johnson',
        studentAvatarId: 'testimonial-avatar-2',
        rating: 5,
        reviewText: "Sarah is an amazing calculus tutor! She explains concepts clearly and is very patient. I wouldn't have passed without her.",
        date: '2023-09-01',
    },
    {
        id: 2,
        tutorId: 1,
        studentId: 'user-maria-garcia',
        studentName: 'Maria Garcia',
        studentAvatarId: 'testimonial-avatar-3',
        rating: 5,
        reviewText: "Her methods for teaching linear algebra are fantastic. Highly recommended!",
        date: '2023-08-15',
    },
     {
        id: 3,
        tutorId: 1,
        studentId: 'user-ben-carter',
        studentName: 'Ben Carter',
        studentAvatarId: 'tutor-avatar-7',
        rating: 5,
        reviewText: "Emma's passion for physics is contagious. She made thermodynamics much less intimidating.",
        date: '2023-09-05',
    },
    {
        id: 4,
        tutorId: 1,
        studentId: 'user-chloe-kim',
        studentName: 'Chloe Kim',
        studentAvatarId: 'testimonial-avatar-1',
        rating: 5,
        reviewText: "Michael is a coding wizard. He helped me debug my project and understand data structures on a much deeper level.",
        date: '2023-09-10',
    },
     {
        id: 5,
        tutorId: 1,
        studentId: 'user-leo-martinez',
        studentName: 'Leo Martinez',
        studentAvatarId: 'testimonial-avatar-2',
        rating: 5,
        reviewText: "Best Java tutor I've ever had. His real-world examples from his software dev job were super helpful.",
        date: '2023-08-22',
    },
    {
        id: 6,
        tutorId: 1,
        studentId: 'user-sophia-lee',
        studentName: 'Sophia Lee',
        studentAvatarId: 'testimonial-avatar-3',
        rating: 5,
        reviewText: "Great at explaining algorithms. A bit fast-paced at times, but always willing to go back and clarify.",
        date: '2023-08-18',
    },
];
