export const tutors = [
  {
    id: 1,
    name: 'Sarah Williams',
    rating: 4.9,
    reviews: 127,
    experience: 5,
    subjects: ['Calculus', 'Linear Algebra'],
    bio: 'Passionate and experienced math tutor dedicated to making complex concepts easy to understand.',
    avatarId: 'tutor-avatar-1',
  },
  {
    id: 2,
    name: 'Emma Rodriguez',
    rating: 4.8,
    reviews: 89,
    experience: 4,
    subjects: ['Thermodynamics', 'Physics II'],
    bio: 'Mechanical engineer with a love for teaching. I specialize in helping students excel in advanced physics.',
    avatarId: 'tutor-avatar-2',
  },
  {
    id: 3,
    name: 'Michael Chen',
    rating: 4.9,
    reviews: 95,
    experience: 3,
    subjects: ['Data Structures', 'Algorithms', 'Java'],
    bio: 'Software developer with a knack for breaking down complex programming topics for aspiring coders.',
    avatarId: 'tutor-avatar-3',
  },
  {
    id: 4,
    name: 'Jessica Lee',
    rating: 4.7,
    reviews: 95,
    experience: 3,
    subjects: ['Organic Chemistry', 'Biochemistry'],
    bio: 'PhD candidate in Chemistry, excited to help students navigate the challenges of organic chemistry.',
    avatarId: 'tutor-avatar-4',
  },
  {
    id: 5,
    name: 'David Kim',
    rating: 4.8,
    reviews: 95,
    experience: 3,
    subjects: ['US History', 'World History', 'Government'],
    bio: 'History enthusiast with a Masters in Education. I aim to make history engaging and relevant.',
    avatarId: 'tutor-avatar-5',
  },
  {
    id: 6,
    name: 'Emily White',
    rating: 5.0,
    reviews: 95,
    experience: 3,
    subjects: ['English Literature', 'Creative Writing'],
    bio: 'Published author and long-time writing instructor. I help students find their voice and craft compelling essays.',
    avatarId: 'tutor-avatar-6',
  },
    {
    id: 7,
    name: 'Chris John',
    rating: 4.6,
    reviews: 95,
    experience: 3,
    subjects: ['Algebra', 'Geometry', 'Trigonometry'],
    bio: 'Mathematics graduate with a passion for helping students build a strong foundation in math.',
    avatarId: 'tutor-avatar-7',
  },
  {
    id: 8,
    name: 'Olivia Martinez',
    rating: 4.9,
    reviews: 95,
    experience: 3,
    subjects: ['Spanish', 'French'],
    bio: 'Native Spanish speaker and fluent in French. I offer immersive lessons for all skill levels.',
    avatarId: 'tutor-avatar-8',
  },
  {
    id: 9,
    name: 'James Brown',
    rating: 4.7,
    reviews: 95,
    experience: 3,
    subjects: ['Macroeconomics', 'Microeconomics'],
    bio: 'Economics graduate from a top university, skilled at simplifying economic theories and models.',
    avatarId: 'tutor-avatar-9',
  },
];
